# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI_REXS_SCAN.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QGroupBox, QHBoxLayout, QLCDNumber, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QProgressBar, QPushButton, QSizePolicy, QSpacerItem,
    QSplitter, QStatusBar, QTabWidget, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1242, 867)
        MainWindow.setMinimumSize(QSize(1000, 800))
        MainWindow.setAutoFillBackground(False)
        self.actionView_data = QAction(MainWindow)
        self.actionView_data.setObjectName(u"actionView_data")
        self.actionDatabase = QAction(MainWindow)
        self.actionDatabase.setObjectName(u"actionDatabase")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_4 = QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.Scan_infobox = QGroupBox(self.centralwidget)
        self.Scan_infobox.setObjectName(u"Scan_infobox")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scan_infobox.sizePolicy().hasHeightForWidth())
        self.Scan_infobox.setSizePolicy(sizePolicy)
        self.Scan_infobox.setMinimumSize(QSize(600, 160))
        self.gridLayout = QGridLayout(self.Scan_infobox)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.Select_endstation_cbx = QComboBox(self.Scan_infobox)
        self.Select_endstation_cbx.addItem("")
        self.Select_endstation_cbx.addItem("")
        self.Select_endstation_cbx.addItem("")
        self.Select_endstation_cbx.setObjectName(u"Select_endstation_cbx")
        self.Select_endstation_cbx.setMinimumSize(QSize(100, 40))
        self.Select_endstation_cbx.setMaximumSize(QSize(220, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 85, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(180, 249, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush2 = QBrush(QColor(255, 0, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush3 = QBrush(QColor(240, 240, 240, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush4 = QBrush(QColor(0, 120, 215, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.Select_endstation_cbx.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(12)
        font.setBold(True)
        self.Select_endstation_cbx.setFont(font)
        self.Select_endstation_cbx.setLayoutDirection(Qt.LeftToRight)
        self.Select_endstation_cbx.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(180, 249, 255);")

        self.verticalLayout_6.addWidget(self.Select_endstation_cbx)

        self.Select_instrument_cbx = QComboBox(self.Scan_infobox)
        self.Select_instrument_cbx.addItem("")
        self.Select_instrument_cbx.addItem("")
        self.Select_instrument_cbx.setObjectName(u"Select_instrument_cbx")
        self.Select_instrument_cbx.setMinimumSize(QSize(100, 40))
        self.Select_instrument_cbx.setMaximumSize(QSize(220, 16777215))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.Select_instrument_cbx.setPalette(palette1)
        self.Select_instrument_cbx.setFont(font)
        self.Select_instrument_cbx.setLayoutDirection(Qt.LeftToRight)
        self.Select_instrument_cbx.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(180, 249, 255);")

        self.verticalLayout_6.addWidget(self.Select_instrument_cbx)

        self.Scan_Channel_cbx = QComboBox(self.Scan_infobox)
        self.Scan_Channel_cbx.setObjectName(u"Scan_Channel_cbx")
        self.Scan_Channel_cbx.setMinimumSize(QSize(100, 40))
        self.Scan_Channel_cbx.setMaximumSize(QSize(220, 16777215))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.Scan_Channel_cbx.setPalette(palette2)
        self.Scan_Channel_cbx.setFont(font)
        self.Scan_Channel_cbx.setLayoutDirection(Qt.LeftToRight)
        self.Scan_Channel_cbx.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(180, 249, 255);")

        self.verticalLayout_6.addWidget(self.Scan_Channel_cbx)


        self.horizontalLayout_2.addLayout(self.verticalLayout_6)

        self.Instrument_tab = QTabWidget(self.Scan_infobox)
        self.Instrument_tab.setObjectName(u"Instrument_tab")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Instrument_tab.sizePolicy().hasHeightForWidth())
        self.Instrument_tab.setSizePolicy(sizePolicy1)
        self.Instrument_tab.setMinimumSize(QSize(200, 125))
        self.Instrument_tab.setMaximumSize(QSize(800, 16777215))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        brush5 = QBrush(QColor(0, 170, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        brush7 = QBrush(QColor(120, 120, 120, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.Instrument_tab.setPalette(palette3)
        self.Instrument_tab.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_4 = QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.ADC_TEY_checkBox = QCheckBox(self.tab)
        self.ADC_TEY_checkBox.setObjectName(u"ADC_TEY_checkBox")
        self.ADC_TEY_checkBox.setCheckable(True)
        self.ADC_TEY_checkBox.setChecked(True)

        self.verticalLayout_4.addWidget(self.ADC_TEY_checkBox)

        self.ADC_Au_checkBox = QCheckBox(self.tab)
        self.ADC_Au_checkBox.setObjectName(u"ADC_Au_checkBox")
        self.ADC_Au_checkBox.setAutoFillBackground(False)
        self.ADC_Au_checkBox.setCheckable(True)
        self.ADC_Au_checkBox.setChecked(True)
        self.ADC_Au_checkBox.setAutoRepeat(False)
        self.ADC_Au_checkBox.setTristate(False)

        self.verticalLayout_4.addWidget(self.ADC_Au_checkBox)

        self.ADC_PD_checkBox = QCheckBox(self.tab)
        self.ADC_PD_checkBox.setObjectName(u"ADC_PD_checkBox")
        self.ADC_PD_checkBox.setChecked(True)

        self.verticalLayout_4.addWidget(self.ADC_PD_checkBox)

        self.Instrument_tab.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout_5 = QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.pA_TEY_checkBox = QCheckBox(self.tab_2)
        self.pA_TEY_checkBox.setObjectName(u"pA_TEY_checkBox")
        self.pA_TEY_checkBox.setChecked(True)

        self.verticalLayout_5.addWidget(self.pA_TEY_checkBox)

        self.pA_Au_checkBox = QCheckBox(self.tab_2)
        self.pA_Au_checkBox.setObjectName(u"pA_Au_checkBox")

        self.verticalLayout_5.addWidget(self.pA_Au_checkBox)

        self.pA_PD_checkBox = QCheckBox(self.tab_2)
        self.pA_PD_checkBox.setObjectName(u"pA_PD_checkBox")

        self.verticalLayout_5.addWidget(self.pA_PD_checkBox)

        self.Instrument_tab.addTab(self.tab_2, "")

        self.horizontalLayout_2.addWidget(self.Instrument_tab)

        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.Start_Acqusition_btn = QPushButton(self.Scan_infobox)
        self.Start_Acqusition_btn.setObjectName(u"Start_Acqusition_btn")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(2)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Start_Acqusition_btn.sizePolicy().hasHeightForWidth())
        self.Start_Acqusition_btn.setSizePolicy(sizePolicy2)
        self.Start_Acqusition_btn.setMinimumSize(QSize(200, 40))
        self.Start_Acqusition_btn.setMaximumSize(QSize(220, 16777215))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(14)
        font1.setBold(True)
        self.Start_Acqusition_btn.setFont(font1)
        self.Start_Acqusition_btn.setStyleSheet(u"QPushButton{background-color: rgb(41, 173, 255);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255);border-style:inset;border-top-color: rgb(0, 170, 255);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-top-color: rgb(0, 170, 255);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"QPushButton:pressed{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-bottom-color: rgb(0, 170, 255);border-right-color: rgb(138, 138, 138);\n"
"border-left-color: rgb(56, 56, 56);\n"
"border-top-color: rgb(33, 33, 33);}")

        self.verticalLayout_7.addWidget(self.Start_Acqusition_btn)

        self.Set_range_btn = QPushButton(self.Scan_infobox)
        self.Set_range_btn.setObjectName(u"Set_range_btn")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Set_range_btn.sizePolicy().hasHeightForWidth())
        self.Set_range_btn.setSizePolicy(sizePolicy3)
        self.Set_range_btn.setMinimumSize(QSize(200, 40))
        self.Set_range_btn.setFont(font1)
        self.Set_range_btn.setStyleSheet(u"QPushButton{background-color: rgb(41, 173, 255);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255);border-style:inset;border-top-color: rgb(0, 170, 255);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-top-color: rgb(0, 170, 255);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"QPushButton:pressed{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-bottom-color: rgb(0, 170, 255);border-right-color: rgb(138, 138, 138);\n"
"border-left-color: rgb(56, 56, 56);\n"
"border-top-color: rgb(33, 33, 33);}")

        self.verticalLayout_7.addWidget(self.Set_range_btn)


        self.horizontalLayout_2.addLayout(self.verticalLayout_7)


        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)


        self.horizontalLayout_9.addWidget(self.Scan_infobox)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QSize(300, 150))
        self.gridLayout_5 = QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        sizePolicy3.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy3)
        self.label_9.setMinimumSize(QSize(60, 30))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.label_9.setPalette(palette4)
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_2.addWidget(self.label_9)

        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        sizePolicy3.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy3)
        self.label_7.setMinimumSize(QSize(60, 30))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.label_7.setPalette(palette5)
        self.label_7.setFont(font1)
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_2.addWidget(self.label_7)

        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        sizePolicy3.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy3)
        self.label_6.setMinimumSize(QSize(60, 30))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.label_6.setPalette(palette6)
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_2.addWidget(self.label_6)


        self.horizontalLayout_8.addLayout(self.verticalLayout_2)

        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.Today_label = QLabel(self.groupBox_2)
        self.Today_label.setObjectName(u"Today_label")
        sizePolicy.setHeightForWidth(self.Today_label.sizePolicy().hasHeightForWidth())
        self.Today_label.setSizePolicy(sizePolicy)
        self.Today_label.setMinimumSize(QSize(135, 30))
        self.Today_label.setMaximumSize(QSize(250, 16777215))
        palette7 = QPalette()
        brush8 = QBrush(QColor(0, 193, 142, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        brush9 = QBrush(QColor(37, 226, 255, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush9)
        brush10 = QBrush(QColor(5, 209, 255, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush10)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.Today_label.setPalette(palette7)
        self.Today_label.setFont(font1)
        self.Today_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_9.addWidget(self.Today_label)

        self.UserName_input = QLineEdit(self.groupBox_2)
        self.UserName_input.setObjectName(u"UserName_input")
        self.UserName_input.setMinimumSize(QSize(135, 30))
        self.UserName_input.setMaximumSize(QSize(250, 16777215))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Text, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        self.UserName_input.setPalette(palette8)
        self.UserName_input.setFont(font1)
        self.UserName_input.setStyleSheet(u"")
        self.UserName_input.setAlignment(Qt.AlignCenter)

        self.verticalLayout_9.addWidget(self.UserName_input)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.BeamCurrent_lcd = QLCDNumber(self.groupBox_2)
        self.BeamCurrent_lcd.setObjectName(u"BeamCurrent_lcd")
        self.BeamCurrent_lcd.setMinimumSize(QSize(100, 30))
        self.BeamCurrent_lcd.setMaximumSize(QSize(200, 16777215))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.BeamCurrent_lcd.setPalette(palette9)
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(12)
        self.BeamCurrent_lcd.setFont(font2)
        self.BeamCurrent_lcd.setSmallDecimalPoint(False)
        self.BeamCurrent_lcd.setDigitCount(6)
        self.BeamCurrent_lcd.setProperty("value", 0.000000000000000)
        self.BeamCurrent_lcd.setProperty("intValue", 0)

        self.horizontalLayout_7.addWidget(self.BeamCurrent_lcd)

        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QSize(30, 30))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.label_8.setPalette(palette10)
        self.label_8.setFont(font1)
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_7.addWidget(self.label_8)

        self.SS2_status_label = QLabel(self.groupBox_2)
        self.SS2_status_label.setObjectName(u"SS2_status_label")
        self.SS2_status_label.setFont(font1)
        self.SS2_status_label.setStyleSheet(u"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.SS2_status_label.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_7.addWidget(self.SS2_status_label)


        self.verticalLayout_9.addLayout(self.horizontalLayout_7)


        self.horizontalLayout_8.addLayout(self.verticalLayout_9)


        self.gridLayout_5.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)

        self.Icon_label = QLabel(self.groupBox_2)
        self.Icon_label.setObjectName(u"Icon_label")
        sizePolicy3.setHeightForWidth(self.Icon_label.sizePolicy().hasHeightForWidth())
        self.Icon_label.setSizePolicy(sizePolicy3)
        self.Icon_label.setMinimumSize(QSize(100, 100))

        self.gridLayout_5.addWidget(self.Icon_label, 0, 1, 1, 1)


        self.horizontalLayout_9.addWidget(self.groupBox_2)


        self.verticalLayout_10.addLayout(self.horizontalLayout_9)

        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.layoutWidget = QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.Main_fig_box = QGroupBox(self.layoutWidget)
        self.Main_fig_box.setObjectName(u"Main_fig_box")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.Main_fig_box.sizePolicy().hasHeightForWidth())
        self.Main_fig_box.setSizePolicy(sizePolicy4)
        self.Main_fig_box.setMinimumSize(QSize(400, 400))
        self.Main_fig_box.setMaximumSize(QSize(1900, 16777215))
        self.Main_fig_box.setCursor(QCursor(Qt.CrossCursor))

        self.verticalLayout_3.addWidget(self.Main_fig_box)

        self.groupBox = QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMaximumSize(QSize(16777215, 70))
        self.gridLayout_3 = QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QSize(60, 30))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.label_4.setPalette(palette11)
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_4)

        self.X_axis_set_cbx = QComboBox(self.groupBox)
        self.X_axis_set_cbx.addItem("")
        self.X_axis_set_cbx.addItem("")
        self.X_axis_set_cbx.addItem("")
        self.X_axis_set_cbx.setObjectName(u"X_axis_set_cbx")
        self.X_axis_set_cbx.setMinimumSize(QSize(100, 30))
        self.X_axis_set_cbx.setMaximumSize(QSize(220, 16777215))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Highlight, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Highlight, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.X_axis_set_cbx.setPalette(palette12)
        self.X_axis_set_cbx.setFont(font)
        self.X_axis_set_cbx.setLayoutDirection(Qt.LeftToRight)
        self.X_axis_set_cbx.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(180, 249, 255);")

        self.horizontalLayout_3.addWidget(self.X_axis_set_cbx)

        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QSize(60, 30))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.label_5.setPalette(palette13)
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_5)

        self.Y_axis_set_cbx = QComboBox(self.groupBox)
        self.Y_axis_set_cbx.addItem("")
        self.Y_axis_set_cbx.addItem("")
        self.Y_axis_set_cbx.addItem("")
        self.Y_axis_set_cbx.addItem("")
        self.Y_axis_set_cbx.setObjectName(u"Y_axis_set_cbx")
        self.Y_axis_set_cbx.setMinimumSize(QSize(100, 30))
        self.Y_axis_set_cbx.setMaximumSize(QSize(220, 16777215))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Highlight, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Highlight, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
#endif
        self.Y_axis_set_cbx.setPalette(palette14)
        self.Y_axis_set_cbx.setFont(font)
        self.Y_axis_set_cbx.setLayoutDirection(Qt.LeftToRight)
        self.Y_axis_set_cbx.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(180, 249, 255);")

        self.horizontalLayout_3.addWidget(self.Y_axis_set_cbx)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer)


        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)


        self.verticalLayout_3.addWidget(self.groupBox)

        self.Scan_set_Box = QGroupBox(self.layoutWidget)
        self.Scan_set_Box.setObjectName(u"Scan_set_Box")
        sizePolicy.setHeightForWidth(self.Scan_set_Box.sizePolicy().hasHeightForWidth())
        self.Scan_set_Box.setSizePolicy(sizePolicy)
        self.Scan_set_Box.setMinimumSize(QSize(600, 120))
        self.Scan_set_Box.setMaximumSize(QSize(16777215, 150))
        self.gridLayout_2 = QGridLayout(self.Scan_set_Box)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label = QLabel(self.Scan_set_Box)
        self.label.setObjectName(u"label")
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(50, 30))
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_5.addWidget(self.label)

        self.Min_input = QLineEdit(self.Scan_set_Box)
        self.Min_input.setObjectName(u"Min_input")
        sizePolicy5 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.Min_input.sizePolicy().hasHeightForWidth())
        self.Min_input.setSizePolicy(sizePolicy5)
        self.Min_input.setMinimumSize(QSize(120, 30))
        palette15 = QPalette()
        brush11 = QBrush(QColor(255, 255, 255, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush11)
        brush12 = QBrush(QColor(110, 229, 235, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        self.Min_input.setPalette(palette15)
        self.Min_input.setFont(font1)
        self.Min_input.setFrame(False)
        self.Min_input.setAlignment(Qt.AlignCenter)
        self.Min_input.setReadOnly(True)
        self.Min_input.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.Min_input.setClearButtonEnabled(False)

        self.horizontalLayout_5.addWidget(self.Min_input)

        self.label_2 = QLabel(self.Scan_set_Box)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(30, 30))
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_5.addWidget(self.label_2)

        self.Max_input = QLineEdit(self.Scan_set_Box)
        self.Max_input.setObjectName(u"Max_input")
        sizePolicy5.setHeightForWidth(self.Max_input.sizePolicy().hasHeightForWidth())
        self.Max_input.setSizePolicy(sizePolicy5)
        self.Max_input.setMinimumSize(QSize(120, 30))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        self.Max_input.setPalette(palette16)
        self.Max_input.setFont(font1)
        self.Max_input.setFrame(False)
        self.Max_input.setAlignment(Qt.AlignCenter)
        self.Max_input.setReadOnly(True)
        self.Max_input.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.Max_input.setClearButtonEnabled(False)

        self.horizontalLayout_5.addWidget(self.Max_input)

        self.label_3 = QLabel(self.Scan_set_Box)
        self.label_3.setObjectName(u"label_3")
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QSize(40, 30))
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_5.addWidget(self.label_3)

        self.Num_input = QLineEdit(self.Scan_set_Box)
        self.Num_input.setObjectName(u"Num_input")
        sizePolicy5.setHeightForWidth(self.Num_input.sizePolicy().hasHeightForWidth())
        self.Num_input.setSizePolicy(sizePolicy5)
        self.Num_input.setMinimumSize(QSize(120, 30))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        self.Num_input.setPalette(palette17)
        self.Num_input.setFont(font1)
        self.Num_input.setFrame(False)
        self.Num_input.setAlignment(Qt.AlignCenter)
        self.Num_input.setReadOnly(True)
        self.Num_input.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.Num_input.setClearButtonEnabled(False)

        self.horizontalLayout_5.addWidget(self.Num_input)


        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.Start_scan_btn = QPushButton(self.Scan_set_Box)
        self.Start_scan_btn.setObjectName(u"Start_scan_btn")
        sizePolicy5.setHeightForWidth(self.Start_scan_btn.sizePolicy().hasHeightForWidth())
        self.Start_scan_btn.setSizePolicy(sizePolicy5)
        self.Start_scan_btn.setMinimumSize(QSize(120, 45))
        palette18 = QPalette()
        brush13 = QBrush(QColor(255, 88, 152, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        brush14 = QBrush(QColor(49, 234, 255, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette18.setBrush(QPalette.Active, QPalette.Midlight, brush11)
        brush15 = QBrush(QColor(127, 127, 127, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Dark, brush15)
        brush16 = QBrush(QColor(170, 170, 170, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Mid, brush16)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush13)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush13)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush14)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette18.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush17 = QBrush(QColor(208, 113, 87, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.HighlightedText, brush17)
        palette18.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette18.setBrush(QPalette.Inactive, QPalette.Midlight, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.Dark, brush15)
        palette18.setBrush(QPalette.Inactive, QPalette.Mid, brush16)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush13)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush14)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        brush18 = QBrush(QColor(85, 170, 255, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Inactive, QPalette.Shadow, brush18)
        palette18.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush17)
        palette18.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush13)
#endif
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        palette18.setBrush(QPalette.Disabled, QPalette.Midlight, brush11)
        palette18.setBrush(QPalette.Disabled, QPalette.Dark, brush15)
        palette18.setBrush(QPalette.Disabled, QPalette.Mid, brush16)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush13)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush13)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette18.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush17)
        palette18.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.Start_scan_btn.setPalette(palette18)
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(16)
        font3.setBold(True)
        self.Start_scan_btn.setFont(font3)
        self.Start_scan_btn.setFocusPolicy(Qt.ClickFocus)
        self.Start_scan_btn.setStyleSheet(u"QPushButton{background-color: rgb(49, 234, 255);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(208, 113, 87);color:rgb(255, 88, 152);border-style:inset;border-top-color: rgb(164, 160, 181);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-top-color: rgb(167, 167, 167);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(170, 255, 255);}\n"
"QPushButton:pressed{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-bottom-color: rgb(167, 167, 167);border-right-color: rgb(138, 138, 138);\n"
"border-left-color: rgb(56, 56, 56);\n"
"border-top-color:rgb(167, 167, 16"
                        "7);}")
        self.Start_scan_btn.setCheckable(False)
        self.Start_scan_btn.setAutoDefault(False)
        self.Start_scan_btn.setFlat(False)

        self.horizontalLayout_6.addWidget(self.Start_scan_btn)

        self.Stop_scan_btn = QPushButton(self.Scan_set_Box)
        self.Stop_scan_btn.setObjectName(u"Stop_scan_btn")
        sizePolicy5.setHeightForWidth(self.Stop_scan_btn.sizePolicy().hasHeightForWidth())
        self.Stop_scan_btn.setSizePolicy(sizePolicy5)
        self.Stop_scan_btn.setMinimumSize(QSize(120, 45))
        self.Stop_scan_btn.setFont(font3)
        self.Stop_scan_btn.setFocusPolicy(Qt.WheelFocus)
        self.Stop_scan_btn.setStyleSheet(u"QPushButton{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color:rgb(255, 255, 255);border-style:inset;border-top-color: rgb(164, 160, 181);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"\n"
"QPushButton:hover{background-color:rgb(49, 234, 255);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color:rgb(255, 91, 58) ;border-style:inset;border-top-color: rgb(134, 255, 255);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(255, 255, 255);}\n"
"QPushButton:pressed{background-color:rgb(33, 190, 193);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-bottom-color: rgb(134, 255, 255);border-right-color: rgb(138, 138, 138);\n"
"border-left-color: rgb(56, 56, 56);\n"
"border-top-color: rgb(33, 33, 33);}")

        self.horizontalLayout_6.addWidget(self.Stop_scan_btn)

        self.Clear_Save_btn = QPushButton(self.Scan_set_Box)
        self.Clear_Save_btn.setObjectName(u"Clear_Save_btn")
        sizePolicy5.setHeightForWidth(self.Clear_Save_btn.sizePolicy().hasHeightForWidth())
        self.Clear_Save_btn.setSizePolicy(sizePolicy5)
        self.Clear_Save_btn.setMinimumSize(QSize(120, 45))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette19.setBrush(QPalette.Active, QPalette.Midlight, brush11)
        palette19.setBrush(QPalette.Active, QPalette.Dark, brush15)
        palette19.setBrush(QPalette.Active, QPalette.Mid, brush16)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush13)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush13)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush14)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette19.setBrush(QPalette.Active, QPalette.HighlightedText, brush17)
        palette19.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette19.setBrush(QPalette.Inactive, QPalette.Midlight, brush11)
        palette19.setBrush(QPalette.Inactive, QPalette.Dark, brush15)
        palette19.setBrush(QPalette.Inactive, QPalette.Mid, brush16)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush13)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush14)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Inactive, QPalette.Shadow, brush18)
        palette19.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush17)
        palette19.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush13)
#endif
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Midlight, brush11)
        palette19.setBrush(QPalette.Disabled, QPalette.Dark, brush15)
        palette19.setBrush(QPalette.Disabled, QPalette.Mid, brush16)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush13)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush13)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette19.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette19.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush17)
        palette19.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.Clear_Save_btn.setPalette(palette19)
        self.Clear_Save_btn.setFont(font3)
        self.Clear_Save_btn.setFocusPolicy(Qt.ClickFocus)
        self.Clear_Save_btn.setStyleSheet(u"QPushButton{background-color: rgb(49, 234, 255);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(208, 113, 87);color:rgb(255, 88, 152);border-style:inset;border-top-color: rgb(164, 160, 181);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-top-color: rgb(167, 167, 167);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(170, 255, 255);}\n"
"QPushButton:pressed{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-bottom-color: rgb(167, 167, 167);border-right-color: rgb(138, 138, 138);\n"
"border-left-color: rgb(56, 56, 56);\n"
"border-top-color:rgb(167, 167, 16"
                        "7);}")
        self.Clear_Save_btn.setCheckable(False)
        self.Clear_Save_btn.setAutoDefault(False)
        self.Clear_Save_btn.setFlat(False)

        self.horizontalLayout_6.addWidget(self.Clear_Save_btn)

        self.Calculate_btn = QPushButton(self.Scan_set_Box)
        self.Calculate_btn.setObjectName(u"Calculate_btn")
        sizePolicy5.setHeightForWidth(self.Calculate_btn.sizePolicy().hasHeightForWidth())
        self.Calculate_btn.setSizePolicy(sizePolicy5)
        self.Calculate_btn.setMinimumSize(QSize(120, 45))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette20.setBrush(QPalette.Active, QPalette.Midlight, brush11)
        palette20.setBrush(QPalette.Active, QPalette.Dark, brush15)
        palette20.setBrush(QPalette.Active, QPalette.Mid, brush16)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush13)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush13)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush14)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette20.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette20.setBrush(QPalette.Active, QPalette.HighlightedText, brush17)
        palette20.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette20.setBrush(QPalette.Inactive, QPalette.Midlight, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.Dark, brush15)
        palette20.setBrush(QPalette.Inactive, QPalette.Mid, brush16)
        palette20.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush13)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush14)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette20.setBrush(QPalette.Inactive, QPalette.Shadow, brush18)
        palette20.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush17)
        palette20.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush13)
#endif
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        palette20.setBrush(QPalette.Disabled, QPalette.Midlight, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Dark, brush15)
        palette20.setBrush(QPalette.Disabled, QPalette.Mid, brush16)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush13)
        palette20.setBrush(QPalette.Disabled, QPalette.ButtonText, brush13)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette20.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette20.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush17)
        palette20.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.Calculate_btn.setPalette(palette20)
        self.Calculate_btn.setFont(font3)
        self.Calculate_btn.setFocusPolicy(Qt.ClickFocus)
        self.Calculate_btn.setStyleSheet(u"QPushButton{background-color: rgb(49, 234, 255);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(208, 113, 87);color:rgb(255, 88, 152);border-style:inset;border-top-color:rgb(164, 160, 181);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(33, 33, 33);}\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-top-color: rgb(167, 167, 167);border-left-color: rgb(138, 138, 138);\n"
"border-right-color: rgb(56, 56, 56);\n"
"border-bottom-color: rgb(170, 255, 255);}\n"
"QPushButton:pressed{background-color:rgb(255, 91, 58);border:2px;border-radius:10px;padding:2px 4px;selection-color: rgb(255, 85, 127);color: rgb(255, 255, 255) ;border-style:inset;border-bottom-color: rgb(167, 167, 167);border-right-color: rgb(138, 138, 138);\n"
"border-left-color: rgb(56, 56, 56);\n"
"border-top-color:rgb(167, 167, 167"
                        ");}")
        self.Calculate_btn.setCheckable(False)
        self.Calculate_btn.setAutoDefault(False)
        self.Calculate_btn.setFlat(False)

        self.horizontalLayout_6.addWidget(self.Calculate_btn)


        self.verticalLayout.addLayout(self.horizontalLayout_6)


        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)


        self.verticalLayout_3.addWidget(self.Scan_set_Box)

        self.splitter_2.addWidget(self.layoutWidget)
        self.splitter = QSplitter(self.splitter_2)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Vertical)
        self.Monitor_Tab = QTabWidget(self.splitter)
        self.Monitor_Tab.setObjectName(u"Monitor_Tab")
        self.Monitor_Tab.setMinimumSize(QSize(400, 400))
        palette21 = QPalette()
        brush19 = QBrush(QColor(255, 85, 127, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush19)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        self.Monitor_Tab.setPalette(palette21)
        self.Monitor_Tab.setFont(font1)
        self.Monitor_Tab.setTabPosition(QTabWidget.South)
        self.Monitor_Tab.setTabShape(QTabWidget.Rounded)
        self.Monitor_Tab.setMovable(True)
        self.splitter.addWidget(self.Monitor_Tab)
        self.info_textbox = QTextEdit(self.splitter)
        self.info_textbox.setObjectName(u"info_textbox")
        self.info_textbox.setEnabled(True)
        sizePolicy6 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.info_textbox.sizePolicy().hasHeightForWidth())
        self.info_textbox.setSizePolicy(sizePolicy6)
        self.info_textbox.setMinimumSize(QSize(100, 100))
        self.info_textbox.setMaximumSize(QSize(1800, 300))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.Text, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette22.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        self.info_textbox.setPalette(palette22)
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(10)
        font4.setBold(False)
        self.info_textbox.setFont(font4)
        self.info_textbox.setAcceptDrops(True)
        self.info_textbox.setReadOnly(True)
        self.splitter.addWidget(self.info_textbox)
        self.splitter_2.addWidget(self.splitter)

        self.verticalLayout_8.addWidget(self.splitter_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setMinimumSize(QSize(200, 0))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(True)

        self.horizontalLayout_4.addWidget(self.progressBar)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.Now_time = QLabel(self.centralwidget)
        self.Now_time.setObjectName(u"Now_time")
        sizePolicy1.setHeightForWidth(self.Now_time.sizePolicy().hasHeightForWidth())
        self.Now_time.setSizePolicy(sizePolicy1)
        self.Now_time.setMinimumSize(QSize(190, 30))
        self.Now_time.setMaximumSize(QSize(1000, 40))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        brush20 = QBrush(QColor(44, 213, 196, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette23.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette23.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette23.setBrush(QPalette.Active, QPalette.Base, brush20)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette23.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.Base, brush20)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette23.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush20)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.Now_time.setPalette(palette23)
        self.Now_time.setFont(font1)
        self.Now_time.setStyleSheet(u"background-color: rgb(44, 213, 196);\n"
"color:rgb(255, 255, 255)")
        self.Now_time.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.Now_time)

        self.Done_time = QLabel(self.centralwidget)
        self.Done_time.setObjectName(u"Done_time")
        sizePolicy1.setHeightForWidth(self.Done_time.sizePolicy().hasHeightForWidth())
        self.Done_time.setSizePolicy(sizePolicy1)
        self.Done_time.setMinimumSize(QSize(190, 30))
        self.Done_time.setMaximumSize(QSize(1000, 40))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette24.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette24.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette24.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette24.setBrush(QPalette.Active, QPalette.Base, brush20)
        palette24.setBrush(QPalette.Active, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette24.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette24.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.Base, brush20)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette24.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette24.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush20)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette24.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.Done_time.setPalette(palette24)
        self.Done_time.setFont(font1)
        self.Done_time.setStyleSheet(u"background-color: rgb(44, 213, 196);\n"
"color:rgb(255, 255, 255)")
        self.Done_time.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.Done_time)

        self.Cost_time = QLabel(self.centralwidget)
        self.Cost_time.setObjectName(u"Cost_time")
        sizePolicy1.setHeightForWidth(self.Cost_time.sizePolicy().hasHeightForWidth())
        self.Cost_time.setSizePolicy(sizePolicy1)
        self.Cost_time.setMinimumSize(QSize(190, 30))
        self.Cost_time.setMaximumSize(QSize(1000, 40))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette25.setBrush(QPalette.Active, QPalette.Button, brush20)
        palette25.setBrush(QPalette.Active, QPalette.Text, brush11)
        palette25.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette25.setBrush(QPalette.Active, QPalette.Base, brush20)
        palette25.setBrush(QPalette.Active, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette25.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush20)
        palette25.setBrush(QPalette.Inactive, QPalette.Text, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.Base, brush20)
        palette25.setBrush(QPalette.Inactive, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette25.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush20)
        palette25.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.Base, brush20)
        palette25.setBrush(QPalette.Disabled, QPalette.Window, brush20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette25.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.Cost_time.setPalette(palette25)
        self.Cost_time.setFont(font1)
        self.Cost_time.setStyleSheet(u"background-color: rgb(44, 213, 196);\n"
"color:rgb(255, 255, 255)")
        self.Cost_time.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.Cost_time)


        self.horizontalLayout_4.addLayout(self.horizontalLayout)


        self.verticalLayout_8.addLayout(self.horizontalLayout_4)


        self.verticalLayout_10.addLayout(self.verticalLayout_8)


        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1242, 28))
        self.menubar.setFont(font1)
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        self.menuMenu.setFont(font)
        self.menuAnalysis = QMenu(self.menubar)
        self.menuAnalysis.setObjectName(u"menuAnalysis")
        self.menuAnalysis.setFont(font)
        self.menuInstrument = QMenu(self.menubar)
        self.menuInstrument.setObjectName(u"menuInstrument")
        self.menuInstrument.setFont(font)
        self.menuhelp = QMenu(self.menubar)
        self.menuhelp.setObjectName(u"menuhelp")
        self.menuhelp.setFont(font)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuInstrument.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())
        self.menuAnalysis.addAction(self.actionView_data)
        self.menuAnalysis.addAction(self.actionDatabase)
        self.menuhelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        self.Instrument_tab.setCurrentIndex(1)
        self.Start_scan_btn.setDefault(False)
        self.Clear_Save_btn.setDefault(False)
        self.Calculate_btn.setDefault(False)
        self.Monitor_Tab.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionView_data.setText(QCoreApplication.translate("MainWindow", u"View_data", None))
        self.actionDatabase.setText(QCoreApplication.translate("MainWindow", u"Database", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.Scan_infobox.setTitle(QCoreApplication.translate("MainWindow", u"Scan_info", None))
        self.Select_endstation_cbx.setItemText(0, QCoreApplication.translate("MainWindow", u"REXS_\u6563\u5c04\u7ad9", None))
        self.Select_endstation_cbx.setItemText(1, QCoreApplication.translate("MainWindow", u"RXES_\u53d1\u5c04\u8c31\u7ad9", None))
        self.Select_endstation_cbx.setItemText(2, QCoreApplication.translate("MainWindow", u"O-REXS_\u6709\u673a\u6563\u5c04", None))

        self.Select_instrument_cbx.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7535\u6d41\u653e\u5927\u5668ADC", None))
        self.Select_instrument_cbx.setItemText(1, QCoreApplication.translate("MainWindow", u"\u76ae\u5b89\u8ba1pAmeter", None))

        self.ADC_TEY_checkBox.setText(QCoreApplication.translate("MainWindow", u"TEY_V", None))
        self.ADC_Au_checkBox.setText(QCoreApplication.translate("MainWindow", u"Au_V", None))
        self.ADC_PD_checkBox.setText(QCoreApplication.translate("MainWindow", u"PD_V", None))
        self.Instrument_tab.setTabText(self.Instrument_tab.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"ADC_DAQ", None))
        self.pA_TEY_checkBox.setText(QCoreApplication.translate("MainWindow", u"TEY_I", None))
        self.pA_Au_checkBox.setText(QCoreApplication.translate("MainWindow", u"Au_I", None))
        self.pA_PD_checkBox.setText(QCoreApplication.translate("MainWindow", u"PD_I", None))
        self.Instrument_tab.setTabText(self.Instrument_tab.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"pAmeter", None))
#if QT_CONFIG(tooltip)
        self.Start_Acqusition_btn.setToolTip(QCoreApplication.translate("MainWindow", u"Connect Electrometer6514", None))
#endif // QT_CONFIG(tooltip)
        self.Start_Acqusition_btn.setText(QCoreApplication.translate("MainWindow", u"Start Acqusition", None))
        self.Set_range_btn.setText(QCoreApplication.translate("MainWindow", u"Set Scan Range", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Operator-Beamline", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Today:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Beam:", None))
        self.Today_label.setText("")
        self.UserName_input.setText("")
        self.UserName_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter UserName", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.SS2_status_label.setText(QCoreApplication.translate("MainWindow", u"on", None))
        self.Icon_label.setText("")
        self.Main_fig_box.setTitle(QCoreApplication.translate("MainWindow", u"MainFigure", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Plot_set", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"X axis:", None))
        self.X_axis_set_cbx.setItemText(0, QCoreApplication.translate("MainWindow", u"ReadBack", None))
        self.X_axis_set_cbx.setItemText(1, QCoreApplication.translate("MainWindow", u"SetPoint", None))
        self.X_axis_set_cbx.setItemText(2, QCoreApplication.translate("MainWindow", u"Timestamp", None))

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Y axis:", None))
        self.Y_axis_set_cbx.setItemText(0, QCoreApplication.translate("MainWindow", u"TEY", None))
        self.Y_axis_set_cbx.setItemText(1, QCoreApplication.translate("MainWindow", u"Au", None))
        self.Y_axis_set_cbx.setItemText(2, QCoreApplication.translate("MainWindow", u"Normalized", None))
        self.Y_axis_set_cbx.setItemText(3, QCoreApplication.translate("MainWindow", u"PD", None))

        self.Scan_set_Box.setTitle(QCoreApplication.translate("MainWindow", u"Scan_Set", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"From", None))
        self.Min_input.setInputMask("")
        self.Min_input.setText("")
        self.Min_input.setPlaceholderText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"To", None))
        self.Max_input.setInputMask("")
        self.Max_input.setText("")
        self.Max_input.setPlaceholderText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Num", None))
        self.Num_input.setInputMask("")
        self.Num_input.setText("")
        self.Num_input.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.Start_scan_btn.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Start_scan_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"begin scan,should choose scan mode and scan range", None))
#endif // QT_CONFIG(statustip)
        self.Start_scan_btn.setText(QCoreApplication.translate("MainWindow", u"Start_Scan", None))
#if QT_CONFIG(tooltip)
        self.Stop_scan_btn.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Stop_scan_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"Stop scan", None))
#endif // QT_CONFIG(statustip)
        self.Stop_scan_btn.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
#if QT_CONFIG(tooltip)
        self.Clear_Save_btn.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Clear_Save_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"begin scan,should choose scan mode and scan range", None))
#endif // QT_CONFIG(statustip)
        self.Clear_Save_btn.setText(QCoreApplication.translate("MainWindow", u"Clear+Save", None))
#if QT_CONFIG(tooltip)
        self.Calculate_btn.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.Calculate_btn.setStatusTip(QCoreApplication.translate("MainWindow", u"begin scan,should choose scan mode and scan range", None))
#endif // QT_CONFIG(statustip)
        self.Calculate_btn.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.info_textbox.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:'Arial'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">start program...</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p></body></html>", None))
        self.Now_time.setText("")
        self.Done_time.setText("")
        self.Cost_time.setText("")
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.menuAnalysis.setTitle(QCoreApplication.translate("MainWindow", u"Analysis", None))
        self.menuInstrument.setTitle(QCoreApplication.translate("MainWindow", u"Instrument", None))
        self.menuhelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

